config/routes.rb
Rails.application.routes.draw do
  resources :blogs, path: '/' do
    put :share_count
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  before_create :set_full_name
  has_many :blogs

  def set_full_name
    self.full_name = [first_name, last_name].join(' ')
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :author

  def self.search(search)
    if search
      joins(:author).where('Lower(title) LIKE Lower(:search) OR Lower(preview_text) LIKE Lower(:search) 
        OR Lower(body) LIKE Lower(:search) OR Lower(authors.first_name) LIKE Lower(:search) OR 
        Lower(authors.last_name) LIKE Lower(:search) OR Lower(authors.full_name) LIKE Lower(:search)', search: "%#{search}%")
    else
      find(:all)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @blogs = Blog.search(params[:search]) unless params[:search].blank?
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def share_count
    @blog = Blog.find(params[:blog_id])
    @blog.increment!(:shared_blog_count)
    redirect_back(fallback_location: blogs_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :preview_text, :body, :author_id, :shared_blog_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label for="title">Title</label>
    <%= form.text_field :title, class: "form-control", id: "title", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <label for="author">Author</label>
    <%= form.collection_select :author_id, Author.all, :id, :set_full_name, {prompt: "Select"}, autofocus:true, class: "form-control", id: "author" %>
  </div>
  <div class="form-group">
    <label for="preview_text">Preview Text</label>
    <%= form.text_area :preview_text, class: "form-control", :class => "tinymce", id: "preview_text", :rows => 10, :cols => 80, placeholder: "Preview Text" %>
  </div>
  <div class="form-group">
    <label for="body">Body</label>
    <%= form.text_area :body, class: "form-control", :class => "tinymce", id: "body", :rows => 15, :cols => 95, placeholder: "Body" %>
  </div>

  <div class="actions">
     <%= form.submit(@blog.new_record? ? "Create Blog" : "Update Blog ", class: "btn btn-primary") %>
  </div>
<% end %>
<%= tinymce %>

app/views/blogs/edit.html.erb
<div class = "container">
  <h2>Editing Blog</h2>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <span class="float-right">
    <%= link_to 'New', new_blog_path, class: "btn btn-success" %>
  </span>
  <h2 class="mb-5">Blog Posts</h2>
  <% @blogs.each do |blog| %>
    <div>
      <h4><%= blog.title %></h4>
      <p>
        <%= raw blog.preview_text %>
      </p>
      <%= link_to 'Read More', blog, class: "btn btn-link" %>
    </div>
    <hr>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div class = "container">
  <h2>New Blog</h2>
  <%= render 'form', blog: @blog %>
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="content">
    <span class="float-right">
      <%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-primary" %>
      <%= link_to 'Delete', @blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </span>
    <h2><%= @blog.title %></h2>
    <p>by <b><%= @blog.author.set_full_name %></b></p>
    <hr>
    <p>
      <%= raw @blog.body %>
    </p>
    <p>Blog Shared so far:<%= @blog.shared_blog_count %></p>
    <div id="showCount"></div>
    <button type="button" class="btn btn-dark float-right" data-toggle="modal" data-target="#shareModal" onclick="getURL();">Share</button><span class="clearfix"></span>
    <div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel"
      aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="shareModalLabel">Share this blog post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="input-group mb-3">
              <input class="form-control" readonly value="https://share.it/b/9rgiXdySNsW3ggfthaKQCg" id = "url_value"/>
              <div class="input-group-append">
                <button onclick="CountFun()" class="btn btn-success float-right" id="first" >Copy</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  function getURL() {
    return window.location.href;
  }
  document.getElementById("url_value").value = getURL();

  var cnt=0;
  function CountFun(){
    cnt=parseInt(cnt)+parseInt(1);
    var copyText = document.getElementById("url_value");
    copyText.select();
    document.execCommand("copy");
    $('#shareModal').modal('hide');
    alert("URL copied: " + copyText.value);    
  }
  $('#first').click(function(e) {
    e.preventDefault();
  $.ajax({
      type: "PUT",
      url: "<%= blog_share_count_path(@blog) %>"
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OSGApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Blog Example", blogs_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "Home", blogs_path, class: "nav-link" %></li>
    </ul>
    <%= form_tag blogs_path, class: "form-inline my-2 my-lg-0", :method => 'get' do %>
    <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2", type: "search", placeholder: "Search"%>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    <% end %>
  </div>
</nav>